FROM node:20-alpine AS builder
WORKDIR /app
COPY notification-worker/package*.json ./
RUN npm install --only=production

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY notification-worker/ .
EXPOSE 3001
USER node
CMD ["node", "index.js"]